# Generated by Django 4.2.7 on 2026-06-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('specialty', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('avatar_initials', models.CharField(blank=True, max_length=3)),
                ('card_color', models.CharField(default='#a8e6cf', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'therapists',
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
